### ISSUE TITLE
Use symlinks and use "%s" with printf

### ISSUE THREAD

**Issue by hydrargyrum** [Tarrasch/zsh-colors#6]
Since all files have the same content, there could a main command (say, "red") and other colors could just be symlinks to this color ($0 will contain the source of the symlink, not the target). This would also render "template.zsh" and "gen.zsh" useless.

Also, it's better practice to avoid variable strings as first param of `printf`. Prefer using:

    printf %s "$something"

rather than:

    printf "$something"

If `$something` were to contain a "%" (like "%d"), it would be interpreted as the format and try to insert another argument, which would fail. Even if you're certain that `$something` doesn't contain a "%", it's better to follow this as a convention. This avoids anybody stumbling apon your code to ask oneself "can `$something` contain % or not?".
Not using a variable string as format string is *explicitly safe*.
The same advice goes for C's `printf`.

**Comment by Tarrasch** [comment]
> Since all files have the same content, there could a main command (say, "red") and other colors could just be symlinks to this color ($0 will contain the source of the symlink, not the target). This would also render "template.zsh" and "gen.zsh" useless.

I'm not sure about this idea because I'm not sure the content will forever be the same. Furthermore it's confusing to pick one color as the "main color" the others are symlinked too. Lastly color highlighting.

Weighing goods vs bads. I think overall your idea is much better than the current one. But perhaps still have `template.zsh` and the colors symlink to that one. Would that work? It covers 2/3 of the issues I mentioned. :)

-------

As for `printf %s $something`, that is excellent feedback and you explained it clearly to me.

@hydrargyrum. Would you mind sending a PR fixing these issues? I would appreciate it for sure. :)
